# Generated by Django 4.2.4 on 2025-07-06 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='staffAssigned',
            field=models.ManyToManyField(blank=True, related_name='ticketsAssigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
