# Generated by Django 4.2.4 on 2025-07-06 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_ticket_staffassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
